/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type AccountInfoResp struct {

	Id string `json:"id,omitempty"`

	Key string `json:"key,omitempty"`

	Base bool `json:"base,omitempty"`

	// account service properties json
	Properties *interface{} `json:"properties,omitempty"`

	ServerLocation string `json:"server_location,omitempty"`
}
