/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type AccountListRespItems struct {

	Id string `json:"id,omitempty"`

	Hostname string `json:"hostname,omitempty"`

	Plan string `json:"plan,omitempty"`

	Status string `json:"status,omitempty"`

	// true if logged in to this account
	Current bool `json:"current,omitempty"`
}
