/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type AutomationCreateReq struct {

	FileId string `json:"file_id"`

	Action string `json:"action"`

	Status string `json:"status,omitempty"`

	Options *AutomationOptions `json:"options,omitempty"`

	Comment string `json:"comment,omitempty"`

	Expires float32 `json:"expires,omitempty"`

	Email []string `json:"email,omitempty"`
}
