/*
 * Quatrix API
 *
 * Download and upload files or folders, share them with predefined security options, manage your account and profile settings and a lot more functionalities can be easily integrated into your application using our Quatrix APIs. Learn more how to authenticate the Quatrix session, how to construct JSON formatted API calls and what responses to expect in our [API Guide](https://docs.maytech.net/display/MD/API+Guide).
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type AutomationCreateReq struct {

	FileId string `json:"file_id"`

	Action string `json:"action"`

	Status string `json:"status,omitempty"`

	Options *AutomationOptions `json:"options,omitempty"`

	Comment string `json:"comment,omitempty"`

	Expires float32 `json:"expires,omitempty"`

	Email []string `json:"email,omitempty"`
}
