/*
 * Quatrix API
 *
 * Download and upload files or folders, share them with predefined security options, manage your account and profile settings and a lot more functionalities can be easily integrated into your application using our Quatrix APIs. Learn more how to authenticate the Quatrix session, how to construct JSON formatted API calls and what responses to expect in our [API Guide](https://docs.maytech.net/display/MD/API+Guide).
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type AutomationResp struct {

	Id string `json:"id,omitempty"`

	OwnerId string `json:"owner_id,omitempty"`

	FileId string `json:"file_id,omitempty"`

	Created float32 `json:"created,omitempty"`

	Modified float32 `json:"modified,omitempty"`

	Status string `json:"status,omitempty"`

	Action string `json:"action,omitempty"`

	Options *AutomationOptions `json:"options,omitempty"`

	Email []string `json:"email,omitempty"`

	FilePath string `json:"file_path,omitempty"`

	RuleNum float32 `json:"rule_num,omitempty"`
}
