/*
 * Quatrix API
 *
 * Download and upload files or folders, share them with predefined security options, manage your account and profile settings and a lot more functionalities can be easily integrated into your application using our Quatrix APIs. Learn more how to authenticate the Quatrix session, how to construct JSON formatted API calls and what responses to expect in our [API Guide](https://docs.maytech.net/display/MD/API+Guide).
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type BillingUpgradeReq struct {

	QxMaxUsers float32 `json:"qx_max_users,omitempty"`

	SftpMaxUsers float32 `json:"sftp_max_users,omitempty"`

	Currency string `json:"currency"`

	RenewalPeriod string `json:"renewal_period"`

	RecurringRenewal bool `json:"recurring_renewal,omitempty"`

	// package keys
	PackageKeys []string `json:"package_keys,omitempty"`
}
