/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type BillingUpgradeResp struct {

	Status string `json:"status,omitempty"`

	UpgradeInvoiceId string `json:"upgrade_invoice_id,omitempty"`

	InvoiceIds []string `json:"invoice_ids,omitempty"`

	ErrorText string `json:"error_text,omitempty"`
}
