/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type ContactResp struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Email string `json:"email,omitempty"`

	Type_ string `json:"type,omitempty"`

	Status string `json:"status,omitempty"`

	Created int32 `json:"created,omitempty"`

	OwnerId string `json:"owner_id,omitempty"`

	Readonly bool `json:"readonly,omitempty"`

	HasKey bool `json:"has_key,omitempty"`

	Groups []Group `json:"groups,omitempty"`
}
