/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type ContactEditResp struct {

	Name string `json:"name,omitempty"`

	// valid email
	Email string `json:"email,omitempty"`

	// should be 'true' for personal contact
	Personal bool `json:"personal,omitempty"`

	// Group IDs. Could be omitted for site contact.
	Groups []string `json:"groups,omitempty"`
}
