/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type CopyMoveFilesReq struct {

	Ids []string `json:"ids"`

	Target string `json:"target"`

	Resolve bool `json:"resolve,omitempty"`
}
