/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type ErrorModel struct {

	// error details
	Msg string `json:"msg"`

	Code int32 `json:"code"`

	// additional information per call
	Details *interface{} `json:"details,omitempty"`
}
