/*
 * Quatrix API
 *
 * The Quatrix API enables you to automate your interaction with Quatrix using any scripting or programming language. You can test API calls on [Swagger](https://docs.maytech.net/swagger/), the interactive environment we use as the repository for the Quatrix API. In order to authorize to Quatrix API you will need to have a Quatrix account https://yourcompanyname.quatrix.it/ (e.g. https://test-api.quatrix.it/). You can set up a free trial account [here](https://www.maytech.net/freetrial.html#trial=qtrx). Below you'll find information on how to authenticate in a Quatrix session, how to construct JSON formatted API call and what JSON responses to expect.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type FileInfoResp struct {

	// File ID
	Id string `json:"id,omitempty"`

	// File creation timestamp
	Created float32 `json:"created,omitempty"`

	// File modification timestamp
	Modified float32 `json:"modified,omitempty"`

	// File content modification timestamp
	ContentModified float32 `json:"content_modified,omitempty"`

	// File name
	Name string `json:"name,omitempty"`

	// File size in bytes
	Size float32 `json:"size,omitempty"`

	// File type
	Type_ string `json:"type,omitempty"`

	// Owner of Folder/File
	FileOwner *interface{} `json:"file_owner,omitempty"`

	// Role that created/uploaded Folder/File
	ActionRole *interface{} `json:"action_role,omitempty"`

	// Path and Type of path to File
	Paths *interface{} `json:"paths,omitempty"`
}
