/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type FileDiffResp struct {

	From float32 `json:"from,omitempty"`

	To float32 `json:"to,omitempty"`

	Data []FileDiffRespData `json:"data,omitempty"`
}
