/*
 * Quatrix API
 *
 * Download and upload files or folders, share them with predefined security options, manage your account and profile settings and a lot more functionalities can be easily integrated into your application using our Quatrix APIs. Learn more how to authenticate the Quatrix session, how to construct JSON formatted API calls and what responses to expect in our [API Guide](https://docs.maytech.net/display/MD/API+Guide).
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

// File content
type FileCsvResp struct {

	// File Path
	Path string `json:"Path,omitempty"`

	// File name
	Name string `json:"Name,omitempty"`

	// File Size
	Size float32 `json:"Size,omitempty"`

	// File Type (F-file, D-directory, T-trash)
	Type_ string `json:"Type,omitempty"`

	// File creation time
	Created string `json:"Created,omitempty"`

	// File modification time
	Modified string `json:"Modified,omitempty"`

	// File content modification time
	ContentModified string `json:"Content_modified,omitempty"`

	// Who created a file
	CreatedBy *interface{} `json:"Created_by,omitempty"`

	// Who owns a file
	Owner *interface{} `json:"Owner,omitempty"`
}
