/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type FileModifyReq struct {

	Id string `json:"id"`

	Truncate float32 `json:"truncate,omitempty"`

	Name string `json:"name,omitempty"`
}
