/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type FileModifyResp struct {

	Name string `json:"name,omitempty"`

	FileId string `json:"file_id,omitempty"`

	ParentId string `json:"parent_id,omitempty"`

	UploadKey string `json:"upload_key,omitempty"`
}
