/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type FileInfoResp struct {

	// File ID
	Id string `json:"id,omitempty"`

	// File creation timestamp
	Created float32 `json:"created,omitempty"`

	// File modification timestamp
	Modified float32 `json:"modified,omitempty"`

	// File content modification timestamp
	ContentModified float32 `json:"content_modified,omitempty"`

	// File name
	Name string `json:"name,omitempty"`

	// File size in bytes
	Size float32 `json:"size,omitempty"`

	// File type
	Type_ string `json:"type,omitempty"`

	// Owner of Folder/File
	FileOwner *interface{} `json:"file_owner,omitempty"`

	// Role that created/uploaded Folder/File
	ActionRole *interface{} `json:"action_role,omitempty"`

	// Path and Type of path to File
	Paths *interface{} `json:"paths,omitempty"`
}
