/*
 * Quatrix API
 *
 * Download and upload files or folders, share them with predefined security options, manage your account and profile settings and a lot more functionalities can be easily integrated into your application using our Quatrix APIs. Learn more how to authenticate the Quatrix session, how to construct JSON formatted API calls and what responses to expect in our [API Guide](https://docs.maytech.net/display/MD/API+Guide).
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type FilesReturnMetadataResp struct {

	// already created share ID.
	Id string `json:"id,omitempty"`

	Subject string `json:"subject,omitempty"`

	SenderName string `json:"sender_name,omitempty"`

	SenderKey string `json:"sender_key,omitempty"`

	SenderEmail string `json:"sender_email,omitempty"`

	UserName string `json:"user_name,omitempty"`

	UserEmail string `json:"user_email,omitempty"`

	Locale string `json:"locale,omitempty"`

	ReturnPgpEncrypted bool `json:"return_pgp_encrypted,omitempty"`

	Title string `json:"title,omitempty"`

	PgpEnabled bool `json:"pgp_enabled,omitempty"`

	ShareType string `json:"share_type,omitempty"`

	FolderId string `json:"folder_id,omitempty"`

	Activates float32 `json:"activates,omitempty"`

	Expires float32 `json:"expires,omitempty"`

	FilesPerShare float32 `json:"files_per_share,omitempty"`

	Message string `json:"message,omitempty"`
}
