/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type GroupMetadata struct {

	IsSystem bool `json:"is_system,omitempty"`

	TranslationId string `json:"translation_id,omitempty"`

	VisualOrder float32 `json:"visual_order,omitempty"`
}
