/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type GroupResp struct {

	Id string `json:"id,omitempty"`

	ParentId string `json:"parent_id,omitempty"`

	ParentName string `json:"parent_name,omitempty"`

	Name string `json:"name,omitempty"`

	Type_ string `json:"type,omitempty"`

	Operations float32 `json:"operations,omitempty"`

	Users []IdName `json:"users,omitempty"`

	Groups []IdName `json:"groups,omitempty"`

	Metadata *GroupMetadata `json:"metadata,omitempty"`
}
