/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type MakeDirReq struct {

	Target string `json:"target,omitempty"`

	Name string `json:"name,omitempty"`

	Resolve bool `json:"resolve,omitempty"`
}
