/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type PgpKeyRecipientsRespItems struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Created int32 `json:"created,omitempty"`

	Modified int32 `json:"modified,omitempty"`

	Public string `json:"public,omitempty"`

	RecipientId string `json:"recipient_id,omitempty"`

	Email string `json:"email,omitempty"`
}
