/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type ProfileInfoResp struct {

	UserUsed float32 `json:"user_used,omitempty"`

	UserLimit float32 `json:"user_limit,omitempty"`

	AccUsed float32 `json:"acc_used,omitempty"`

	AccLimit float32 `json:"acc_limit,omitempty"`
}
