/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type ProfileSetPasswordReq struct {

	// current password in base64
	Password string `json:"password"`

	// new password in base64
	NewPassword string `json:"new_password"`
}
