/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type ProfileRespShareTypes struct {

	RestrictedShare bool `json:"restricted_share,omitempty"`

	PublicShare bool `json:"public_share,omitempty"`

	TrackedShare bool `json:"tracked_share,omitempty"`
}
