/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type ProjectFoldersListRespItem struct {

	Owner *ProjectOwner `json:"owner,omitempty"`

	ProjectId string `json:"project_id,omitempty"`

	Ctime float32 `json:"ctime,omitempty"`

	Name string `json:"name,omitempty"`

	FileId string `json:"file_id,omitempty"`
}
