/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type ProjectfoldersetusersParams struct {

	Operations float32 `json:"operations,omitempty"`

	ProjectId string `json:"project_id,omitempty"`

	Notify bool `json:"notify,omitempty"`
}
