/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type ProjectOwner struct {

	Email string `json:"email,omitempty"`

	Name string `json:"name,omitempty"`

	Id string `json:"id,omitempty"`
}
