/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type QuicklinkCreateResp struct {

	Id string `json:"id,omitempty"`

	Expires float32 `json:"expires,omitempty"`

	Activates float32 `json:"activates,omitempty"`

	Files []string `json:"files,omitempty"`
}
