/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type SearchQuery struct {

	Tag *TagSearchQueryElement `json:"tag,omitempty"`

	Name *StringSearchQueryElement `json:"name,omitempty"`

	Created *TimestampSearchQueryElement `json:"created,omitempty"`

	Modified *TimestampSearchQueryElement `json:"modified,omitempty"`
}
