/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type SearchTag struct {

	Type_ string `json:"type,omitempty"`

	Value string `json:"value,omitempty"`
}
