/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type SettingsResp struct {

	Title string `json:"title,omitempty"`

	Bcc []string `json:"bcc,omitempty"`

	BillingEmails []string `json:"billing_emails,omitempty"`

	EmailFooter string `json:"email_footer,omitempty"`

	Modified float32 `json:"modified,omitempty"`

	Language string `json:"language,omitempty"`

	PgpEnabled bool `json:"pgp_enabled,omitempty"`

	ShareTypes *interface{} `json:"share_types,omitempty"`

	VirusScan bool `json:"virus_scan,omitempty"`
}
