/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type SettingsAuthMethodsRespItems struct {

	Rank int32 `json:"rank,omitempty"`

	Id string `json:"id,omitempty"`

	Key string `json:"key,omitempty"`
}
