/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type ShareRequestReq struct {

	ReturnPgpEncrypted bool `json:"return_pgp_encrypted,omitempty"`

	SendEmail bool `json:"send_email,omitempty"`

	// List of recipient ids
	Ids []string `json:"ids,omitempty"`

	Message string `json:"message,omitempty"`
}
