/*
 * Quatrix API
 *
 * Download and upload files or folders, share them with predefined security options, manage your account and profile settings and a lot more functionalities can be easily integrated into your application using our Quatrix APIs. Learn more how to authenticate the Quatrix session, how to construct JSON formatted API calls and what responses to expect in our [API Guide](https://docs.maytech.net/display/MD/API+Guide).
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type ShareRequestReq struct {

	// if PGP keys were generated by the sender or the recipient.
	ReturnPgpEncrypted bool `json:"return_pgp_encrypted,omitempty"`

	SendEmail bool `json:"send_email,omitempty"`

	// List of recipient IDs
	Ids []string `json:"ids"`

	Message string `json:"message,omitempty"`

	// Target folder ID for requested files
	FolderId string `json:"folder_id,omitempty"`
}
