/*
 * Quatrix API
 *
 * The Quatrix API enables you to automate your interaction with Quatrix using any scripting or programming language. You can test API calls on [Swagger](https://docs.maytech.net/swagger/), the interactive environment we use as the repository for the Quatrix API. In order to authorize to Quatrix API you will need to have a Quatrix account https://yourcompanyname.quatrix.it/ (e.g. https://test-api.quatrix.it/). You can set up a free trial account [here](https://www.maytech.net/freetrial.html#trial=qtrx). Below you'll find information on how to authenticate in a Quatrix session, how to construct JSON formatted API call and what JSON responses to expect.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type ShareCreateReq struct {

	FolderId string `json:"folder_id"`

	Files []string `json:"files"`

	Contacts []string `json:"contacts"`

	Subject string `json:"subject,omitempty"`

	Message string `json:"message,omitempty"`

	Expires float32 `json:"expires,omitempty"`

	Activates float32 `json:"activates,omitempty"`

	ReturnFiles bool `json:"return_files,omitempty"`

	PgpEncrypted bool `json:"pgp_encrypted,omitempty"`

	ReturnPgpEncrypted bool `json:"return_pgp_encrypted,omitempty"`

	MessageSignature string `json:"message_signature,omitempty"`

	Notify bool `json:"notify,omitempty"`

	ShareType string `json:"share_type,omitempty"`

	Pin string `json:"pin,omitempty"`

	// create share with sending email or just create share
	SendEmail bool `json:"send_email,omitempty"`
}
