/*
 * Quatrix API
 *
 * The Quatrix API enables you to automate your interaction with Quatrix using any scripting or programming language. You can test API calls on [Swagger](https://docs.maytech.net/swagger/), the interactive environment we use as the repository for the Quatrix API. In order to authorize to Quatrix API you will need to have a Quatrix account https://yourcompanyname.quatrix.it/ (e.g. https://test-api.quatrix.it/). You can set up a free trial account [here](https://www.maytech.net/freetrial.html#trial=qtrx). Below you'll find information on how to authenticate in a Quatrix session, how to construct JSON formatted API call and what JSON responses to expect.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type ShareDownloadInfoResp struct {

	Id string `json:"id,omitempty"`

	Message string `json:"message,omitempty"`

	Subject string `json:"subject,omitempty"`

	Activates float32 `json:"activates,omitempty"`

	Expires float32 `json:"expires,omitempty"`

	SenderName string `json:"sender_name,omitempty"`

	SenderEmail string `json:"sender_email,omitempty"`

	// user name from current session
	UserName string `json:"user_name,omitempty"`

	// user email from current session
	UserEmail string `json:"user_email,omitempty"`

	Locale string `json:"locale,omitempty"`

	UserId string `json:"user_id,omitempty"`

	// PGP protected share
	PgpEncrypted bool `json:"pgp_encrypted,omitempty"`

	// for PGP
	PrivateKey string `json:"private_key,omitempty"`

	// Shows that user from current session has PGP key. If True - user will get his private_key.
	PgpEnabled bool `json:"pgp_enabled,omitempty"`

	Status string `json:"status,omitempty"`

	ShareType string `json:"share_type,omitempty"`

	Title string `json:"title,omitempty"`

	Expired bool `json:"expired,omitempty"`

	IsReply bool `json:"is_reply,omitempty"`

	PinProtected bool `json:"pin_protected,omitempty"`
}
