/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type SshKeyResp struct {

	Id string `json:"id,omitempty"`

	Caption string `json:"caption,omitempty"`

	Fingerprint string `json:"fingerprint,omitempty"`

	Modified float32 `json:"modified,omitempty"`

	Expires float32 `json:"expires,omitempty"`

	Status string `json:"status,omitempty"`
}
