/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type TrackingRespItems struct {

	Id string `json:"id,omitempty"`

	Subject string `json:"subject,omitempty"`

	Type_ string `json:"type,omitempty"`

	IsReply bool `json:"is_reply,omitempty"`

	ReleaseDate float32 `json:"release_date,omitempty"`

	ExpireDate float32 `json:"expire_date,omitempty"`

	Created float32 `json:"created,omitempty"`

	Status string `json:"status,omitempty"`

	Email string `json:"email,omitempty"`

	Emails []string `json:"emails,omitempty"`

	OwnerId string `json:"owner_id,omitempty"`

	IsRequest bool `json:"is_request,omitempty"`

	CanReply bool `json:"can_reply,omitempty"`

	Folder string `json:"folder,omitempty"`
}
