/*
 * Quatrix API
 *
 * Download and upload files or folders, share them with predefined security options, manage your account and profile settings and a lot more functionalities can be easily integrated into your application using our Quatrix APIs. Learn more how to authenticate the Quatrix session, how to construct JSON formatted API calls and what responses to expect in our [API Guide](https://docs.maytech.net/display/MD/API+Guide).
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type TrackingActivityRespItems struct {

	Id string `json:"id,omitempty"`

	Email string `json:"email,omitempty"`

	// User name
	UserName string `json:"user_name,omitempty"`

	UserStatus string `json:"user_status,omitempty"`

	Timestamp float32 `json:"timestamp,omitempty"`

	Protocol string `json:"protocol,omitempty"`

	Event string `json:"event,omitempty"`

	Action string `json:"action,omitempty"`

	ShareStatus string `json:"share_status,omitempty"`

	// other information(share id, files, etc)
	Payload *interface{} `json:"payload,omitempty"`

	// duration in seconds
	Duration float32 `json:"duration,omitempty"`
}
