/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type TrackingCsvRespItems struct {

	Time string `json:"Time,omitempty"`

	Event string `json:"Event,omitempty"`

	Action string `json:"Action,omitempty"`

	ClientIPs string `json:"Client IPs,omitempty"`

	UserName string `json:"User name,omitempty"`

	Email string `json:"Email,omitempty"`

	UserStatus string `json:"User status,omitempty"`

	Protocol string `json:"Protocol,omitempty"`

	// other information(share id, files, etc)
	Payload *interface{} `json:"Payload,omitempty"`
}
