/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type TrackingFilesRespItems struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Size float32 `json:"size,omitempty"`

	Type_ string `json:"type,omitempty"`

	Downloads float32 `json:"downloads,omitempty"`
}
