/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type TrackingDownloadsRespItems struct {

	Ip string `json:"ip,omitempty"`

	Name string `json:"name,omitempty"`

	Size float32 `json:"size,omitempty"`

	Duration float32 `json:"duration,omitempty"`

	Time float32 `json:"time,omitempty"`

	Recipient string `json:"recipient,omitempty"`
}
