/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type UserRemoveMfaReq struct {

	Ids []string `json:"ids"`

	AuthType string `json:"auth_type"`
}
