/*
 * Quatrix API
 *
 * The Quatrix API enables you to automate your interaction with Quatrix using any scripting or programming language. You can test API calls on [Swagger](https://docs.maytech.net/swagger/), the interactive environment we use as the repository for the Quatrix API. In order to authorize to Quatrix API you will need to have a Quatrix account https://yourcompanyname.quatrix.it/ (e.g. https://test-api.quatrix.it/). You can set up a free trial account [here](https://www.maytech.net/freetrial.html#trial=qtrx). Below you'll find information on how to authenticate in a Quatrix session, how to construct JSON formatted API call and what JSON responses to expect.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type UserResp struct {

	Id string `json:"id,omitempty"`

	ParentId string `json:"parent_id,omitempty"`

	HomeId string `json:"home_id,omitempty"`

	HomeName string `json:"home_name,omitempty"`

	SuperAdmin string `json:"super_admin,omitempty"`

	Name string `json:"name,omitempty"`

	Email string `json:"email,omitempty"`

	Status string `json:"status,omitempty"`

	Quota float32 `json:"quota,omitempty"`

	Created float32 `json:"created,omitempty"`

	Modified float32 `json:"modified,omitempty"`

	Groups []Group `json:"groups,omitempty"`

	UserOperations float32 `json:"user_operations,omitempty"`

	EffectiveOperations float32 `json:"effective_operations,omitempty"`

	HomeOperations float32 `json:"home_operations,omitempty"`

	Language string `json:"language,omitempty"`

	StorageId string `json:"storage_id,omitempty"`

	HasKey bool `json:"has_key,omitempty"`

	Services []ShortUserService `json:"services,omitempty"`

	UniqueLogin string `json:"unique_login,omitempty"`

	Readonly bool `json:"readonly,omitempty"`

	AuthMethods []string `json:"auth_methods,omitempty"`

	LastLogin float32 `json:"last_login,omitempty"`

	StorageUsed float32 `json:"storage_used,omitempty"`

	ForcedAuth []string `json:"forced_auth,omitempty"`
}
