/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type UserCreateReq struct {

	Name string `json:"name"`

	Email string `json:"email"`

	ParentId string `json:"parent_id,omitempty"`

	Quota float32 `json:"quota,omitempty"`

	Status string `json:"status,omitempty"`

	SuperAdmin string `json:"super_admin,omitempty"`

	HomeId string `json:"home_id,omitempty"`

	UserOperations float32 `json:"user_operations,omitempty"`

	HomeOperations float32 `json:"home_operations,omitempty"`

	Language string `json:"language,omitempty"`

	Groups []string `json:"groups,omitempty"`

	Services []string `json:"services,omitempty"`
}
