/*
 * Quatrix API
 *
 * File Transfer And Sharing API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package quatrix

type WidgetUploadLinkResp struct {

	FileId string `json:"file_id,omitempty"`

	FilePath string `json:"file_path,omitempty"`

	ParentId string `json:"parent_id,omitempty"`

	RoleId string `json:"role_id,omitempty"`
}
